export const openingHours = [
    { period: "morning", hour: "09:00" },
    { period: "morning", hour: "10:00" },
    { period: "morning", hour: "11:00" },
    { period: "morning", hour: "12:00" },
    { period: "afternoon", hour: "13:00" },
    { period: "afternoon", hour: "14:00" },
    { period: "afternoon", hour: "15:00" },
    { period: "afternoon", hour: "16:00" },
    { period: "afternoon", hour: "17:00" },
    { period: "night", hour: "18:00" },
    { period: "night", hour: "19:00" },
    { period: "night", hour: "20:00" },
    { period: "night", hour: "21:00" },
] 
